"""new_field_in user_2

Revision ID: bf3e59fd4a84
Revises: aa23c01821cd
Create Date: 2025-02-28 15:07:47.836819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3e59fd4a84'
down_revision = 'aa23c01821cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.drop_index('ix_post_timestap')
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('timestap')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestap', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.create_index('ix_post_timestap', ['timestap'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
